import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { Header } from '../components/header';
import CreateForm from '../components/createEndpoint';
import EndpointList from '../components/endpointList';
import { EndpointProvider } from '../lib/state';

export default function Home() {
  const { data: session, status } = useSession();
  console.log(session);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container max-w-4xl m-auto mt-4">
        {}
        <h1 className="text-4xl">You are logged in you can create Endpoints</h1>
        <EndpointProvider>
          <CreateForm />
          <EndpointList />
        </EndpointProvider>
      </main>
    </>
  );
}
