import Head from 'next/head';
import { Header } from '../components/header';

export default function Test() {
  return (
    <>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container max-w-2xl m-auto mt-4">
        {}
        <h1 className="text-4xl">Test Page</h1>
      </main>
    </>
  );
}
